Repository apitable/apitable, pull requests merged in 2022-12, with the labels that each got.

#16 chore: cla
  LICENSING.md
  licenses/LICENSE-CLA.md
  packages/components/.gitignore
  packages/components/sonar-project.properties
  packages/datasheet/.env
  packages/datasheet/src/get_env.ts
  packages/datasheet/src/pc/components/address_list/member_info/member_info.tsx
  packages/datasheet/src/pc/components/navigation/account_center_modal/account_center_modal.tsx
  packages/datasheet/src/pc/components/navigation/account_center_modal/basic_setting/basic_setting.tsx
  packages/datasheet/src/pc/components/navigation/account_center_modal/developer_configuration/developer_configuration.tsx
  packages/datasheet/src/pc/components/navigation/user_menu/user_menu.tsx
  packages/datasheet/src/pc/components/space_manage/main_admin/main_admin.tsx
  packages/datasheet/src/pc/components/space_manage/space_info/components/basic_info/index.tsx
  packages/datasheet/src/pc/components/space_manage/space_member_manage/member_table/member_table.tsx
  packages/datasheet/src/pc/components/space_manage/space_member_manage/modal/edit_member_modal/edit_member_modal.tsx
  packages/icons/.gitignore
  packages/icons/.npmignore
  packages/icons/sonar-project.properties
Labels: wontfix

#57 fix: error load space list
  backend-server/application/src/main/java/com/apitable/space/assembler/SpaceAssembler.java
  backend-server/application/src/main/java/com/apitable/space/dto/SpaceDTO.java
  backend-server/application/src/main/java/com/apitable/space/mapper/SpaceMapper.java
  backend-server/application/src/main/java/com/apitable/space/service/impl/SpaceServiceImpl.java
  backend-server/application/src/main/java/com/apitable/space/vo/SpaceVO.java
  backend-server/application/src/main/resources/application.yml
  backend-server/application/src/main/resources/mapper/space/SpaceMapper.xml
  backend-server/application/src/test/java/com/apitable/organization/service/impl/MemberServiceImplTest.java
  backend-server/application/src/test/java/com/apitable/space/mapper/SpaceMapperTest.java
  backend-server/application/src/test/java/com/apitable/space/service/impl/SpaceServiceImplTest.java
Labels: bug

#38 fix: some security vulnerabilities
  packages/core/src/command_manager/command_manager.ts
  packages/core/src/formula_parser/evaluate.ts
  packages/datasheet/src/pc/components/multi_grid/format/format_formula/formula_modal.tsx
  packages/datasheet/src/pc/components/robot/robot_detail/node_form/core/components/fields/NumberField.tsx
  packages/datasheet/src/widget-stage/main/widget/widget_block.tsx
Labels: enhancement
